#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdchar driver"
        aesdchar_load
        ;;
    stop)
        echo "Stopping aesdchar driver"
        aesdchar_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac