#!/bin/sh

case "$1" in
    start)
        echo "Starting ldd modules"
        scull_load
        module_load faulty
        modprobe hello
        ;;
    stop)
        echo "Stopping ldd modules"
        scull_unload
        module_unload faulty
        rmmod hello
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac