#!/bin/sh

case "$1" in
    start)
        echo "loading aesdchar"
        /usr/bin/aesdchar_load
        ;;
    stop)
        echo "removing aesdchar"
        /usr/bin/aesdchar_unload
        ;;
    *)
        echo "Usage: R0 {start|stop}"
        exit 1
esac

exit 0