#! /bin/bash

set -e

WD= pwd
cd /lib/modules/5.15.118-yocto-standard/extra

case "$1" in
    start)
        echo "loading misc-modules"
        module_load hello
        module_load faulty
        ;;
    stop)
        echo "unloading misc-modules"
        module_unload faulty
        module_unload hello
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        cd $WD
        exit 1
esac

exit 0
        