#! /bin/bash

# CONFIG_MD_FAULTY is not set

set -e

case "$1" in
    start)
        echo "loading misc-modules"
        modprobe hello
        insmod /lib/modules/5.15.178-yocto-standard/extra/faulty.ko
        ;;
    stop)
        echo "unloading misc-modules"
        rmmmod faulty
        rmmod hello
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
        