#! /bin/bash

set -e

case "$1" in
    start)
        echo "loading misc-modules"
        module_load faulty
        modprobe hello
        ;;
    stop)
        echo "unloading misc-modules"
        module_unload faulty
        rmmod hello
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
        